package es.in2.issuer.backend.shared.domain.model.dto;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CredentialOfferTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedCredentialIssuer = "https://credential-issuer.example.com";
        Map<String, Grants> expectedGrants = new HashMap<>();
        Grants.TxCode expectedTxCode = new Grants.TxCode(4, "numeric", "description");
        expectedGrants.put("grant1", new Grants("type1", expectedTxCode));
        expectedGrants.put("grant2", new Grants("type2", expectedTxCode));
        List<String> expectedCredentialConfigurationIds = List.of("id1", "id2");
        // Act
        CredentialOffer credentialOffer = new CredentialOffer(
                expectedCredentialIssuer,
                expectedCredentialConfigurationIds,
                expectedGrants
        );
        // Assert
        assertEquals(expectedCredentialIssuer, credentialOffer.credentialIssuer());
        assertEquals(expectedGrants, credentialOffer.grants());
        assertEquals(expectedCredentialConfigurationIds, credentialOffer.credentialConfigurationIds());
    }

    @Test
    void testSetters() {
        // Arrange
        String newCredentialIssuer = "https://new-credential-issuer.example.com";
        Map<String, Grants> newGrants = new HashMap<>();
        // Act
        CredentialOffer credentialOffer = CredentialOffer.builder()
                .credentialIssuer(newCredentialIssuer)
                .grants(newGrants)
                .build();
        // Assert
        assertEquals(newCredentialIssuer, credentialOffer.credentialIssuer());
        assertEquals(newGrants, credentialOffer.grants());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedCredentialIssuer = "https://credential-issuer.example.com";
        Map<String, Grants> expectedGrants = new HashMap<>();
        Grants.TxCode expectedTxCode = new Grants.TxCode(4, "numeric", "description");
        expectedGrants.put("grant1", new Grants("type1", expectedTxCode));
        expectedGrants.put("grant2", new Grants("type2", expectedTxCode));
        List<String> expectedCredentialConfigurationIds = List.of("id1", "id2");
        // Act
        CredentialOffer offer1 = new CredentialOffer(
                expectedCredentialIssuer,
                expectedCredentialConfigurationIds,
                expectedGrants
        );
        CredentialOffer offer2 = new CredentialOffer(
                expectedCredentialIssuer,
                expectedCredentialConfigurationIds,
                expectedGrants
        );
        // Assert
        assertEquals(offer1, offer2); // Tests equals() method generated by Lombok
        assertEquals(offer1.hashCode(), offer2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}