package es.in2.issuer.backend.shared.domain.model.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class GrantsTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedPreAuthorizedCode = "1234";
        Grants.TxCode expectedTxCode = new Grants.TxCode(4, "numeric", "description");
        // Act
        Grants grants = new Grants(expectedPreAuthorizedCode, expectedTxCode);
        // Assert
        assertEquals(expectedPreAuthorizedCode, grants.preAuthorizedCode());
        assertEquals(expectedTxCode, grants.txCode());
    }

    @Test
    void testSetters() {
        // Arrange
        Grants grants = Grants.builder().preAuthorizedCode("5678").txCode(Grants.TxCode.builder().length(6).build()).build();
        // Assert
        assertEquals("5678", grants.preAuthorizedCode());
        assertEquals(6, grants.txCode().length());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedPreAuthorizedCode = "1234";
        Grants.TxCode expectedTxCode = new Grants.TxCode(4, "numeric", "description");
        // Act
        Grants grants1 = new Grants(expectedPreAuthorizedCode, expectedTxCode);
        Grants grants2 = new Grants(expectedPreAuthorizedCode, expectedTxCode);
        // Assert
        assertEquals(grants1, grants2); // Tests equals() method generated by Lombok
        assertEquals(grants1.hashCode(), grants2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}