package es.in2.issuer.backend.shared.domain.model.dto;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ProofTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedProofType = "jwt_vc_json";
        List<String> expectedJwtList = List.of("eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiw....WZwmhmn9OQp6YxX0a2L");
        // Act
        Proofs proof = new Proofs(expectedProofType, expectedJwtList);
        // Assert
        assertEquals(expectedProofType, proof.proofType());
        assertEquals(expectedJwtList, proof.jwt());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedProofType = "jwt_vc_json";
        List<String> expectedJwtList = List.of("eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiw....WZwmhmn9OQp6YxX0a2L");
        // Act
        Proofs dto1 = new Proofs(expectedProofType, expectedJwtList);
        Proofs dto2 = new Proofs(expectedProofType, expectedJwtList);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}