package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class AppNonceValidationResponseDTOTest {

    @Test
    public void testConstructorAndGetters() {
        // Arrange
        String expectedAccessToken = "eyJhbGciOiJSUzI1Ni...yE1XAP-LrbAtaX-wln0wQgdXfu4dephCsMA";

        // Act
        AppNonceValidationResponseDTO dto = new AppNonceValidationResponseDTO(expectedAccessToken);

        // Assert
        assertEquals(expectedAccessToken, dto.getAccessToken());
    }

    @Test
    public void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedAccessToken = "eyJhbGciOiJSUzI1Ni...yE1XAP-LrbAtaX-wln0wQgdXfu4dephCsMA";
        String toStringDto = "AppNonceValidationResponseDTO(accessToken=eyJhbGciOiJSUzI1Ni...yE1XAP-LrbAtaX-wln0wQgdXfu4dephCsMA)";

        // Act
        AppNonceValidationResponseDTO dto1 = new AppNonceValidationResponseDTO(expectedAccessToken);
        AppNonceValidationResponseDTO dto2 = new AppNonceValidationResponseDTO(expectedAccessToken);

        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals(toStringDto, dto1.toString()); // Tests toString() method generated by Lombok
    }

}
