package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AuthenticSourcesGetUserResponseDTOTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        Map<String, Map<String, String>> expectedCredentialSubjectData = new HashMap<>();
        // Add sample data to expectedCredentialSubjectData if needed

        // Act
        AuthenticSourcesGetUserResponseDTO dto = new AuthenticSourcesGetUserResponseDTO(expectedCredentialSubjectData);

        // Assert
        assertEquals(expectedCredentialSubjectData, dto.getCredentialSubjectData());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        Map<String, Map<String, String>> expectedCredentialSubjectData = new HashMap<>();
        // Add sample data to expectedCredentialSubjectData if needed

        String toStringDto = "AuthenticSourcesGetUserResponseDTO(credentialSubjectData=" + expectedCredentialSubjectData + ")";

        // Act
        AuthenticSourcesGetUserResponseDTO dto1 = new AuthenticSourcesGetUserResponseDTO(expectedCredentialSubjectData);
        AuthenticSourcesGetUserResponseDTO dto2 = new AuthenticSourcesGetUserResponseDTO(expectedCredentialSubjectData);

        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals(toStringDto, dto1.toString()); // Tests toString() method generated by Lombok
    }

}
