package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import java.util.Date;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class CommitCredentialDTOTest {

    @Test
    public void testConstructorAndGetters() {
        // Arrange
        UUID expectedCredentialId = UUID.randomUUID();
        String expectedGicarId = "sampleGicarId";
        Date expectedExpirationDate = new Date();

        // Act
        CommitCredentialDTO dto = new CommitCredentialDTO(expectedCredentialId, expectedGicarId, expectedExpirationDate);

        // Assert
        assertEquals(expectedCredentialId, dto.getCredentialId());
        assertEquals(expectedGicarId, dto.getGicarId());
        assertEquals(expectedExpirationDate, dto.getExpirationDate());
    }

    @Test
    public void lombokGeneratedMethodsTest() {
        // Arrange
        UUID expectedCredentialId = UUID.randomUUID();
        String expectedGicarId = "sampleGicarId";
        Date expectedExpirationDate = new Date();

        // Act
        CommitCredentialDTO dto1 = new CommitCredentialDTO(expectedCredentialId, expectedGicarId, expectedExpirationDate);
        CommitCredentialDTO dto2 = new CommitCredentialDTO(expectedCredentialId, expectedGicarId, expectedExpirationDate);

        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("CommitCredentialDTO(credentialId=" + expectedCredentialId +
                ", gicarId=" + expectedGicarId +
                ", expirationDate=" + expectedExpirationDate + ")", dto1.toString()); // Tests toString() method generated by Lombok
    }
}
