package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CredentialResponseErrorTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedError = "sampleError";
        String expectedDescription = "sampleDescription";

        // Act
        CredentialResponseError responseError = new CredentialResponseError(expectedError, expectedDescription);

        // Assert
        assertEquals(expectedError, responseError.getError());
        assertEquals(expectedDescription, responseError.getDescription());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedError = "sampleError";
        String expectedDescription = "sampleDescription";

        // Act
        CredentialResponseError error1 = new CredentialResponseError(expectedError, expectedDescription);
        CredentialResponseError error2 = new CredentialResponseError(expectedError, expectedDescription);

        // Assert
        assertEquals(error1, error2); // Tests equals() method generated by Lombok
        assertEquals(error1.hashCode(), error2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("CredentialResponseError(error=" + expectedError +
                ", description=" + expectedDescription + ")", error1.toString()); // Tests toString() method generated by Lombok
    }
}
