package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CredentialRequestDTOTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedFormat = "sampleFormat";
        ProofDTO expectedProofDTO = new ProofDTO("jwt_vc_json", "sampleJwt");

        // Act
        CredentialRequestDTO credentialRequestDTO = new CredentialRequestDTO(expectedFormat, expectedProofDTO);

        // Assert
        assertEquals(expectedFormat, credentialRequestDTO.getFormat());
        assertEquals(expectedProofDTO, credentialRequestDTO.getProof());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedFormat = "sampleFormat";
        ProofDTO expectedProofDTO = new ProofDTO("jwt_vc_json", "sampleJwt");

        // Act
        CredentialRequestDTO dto1 = new CredentialRequestDTO(expectedFormat, expectedProofDTO);
        CredentialRequestDTO dto2 = new CredentialRequestDTO(expectedFormat, expectedProofDTO);

        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("CredentialRequestDTO(format=" + expectedFormat +
                ", proof=" + expectedProofDTO + ")", dto1.toString()); // Tests toString() method generated by Lombok
    }
}
