package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.assertEquals;

class GenericResponseErrorTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        LocalDateTime expectedTimestamp = LocalDateTime.now();
        int expectedStatus = 500;
        String expectedError = "Internal Server Error";
        String expectedMessage = "Unexpected error occurred";
        String expectedPath = "/api/some-endpoint";

        // Act
        GenericResponseError responseError = new GenericResponseError(
                expectedTimestamp,
                expectedStatus,
                expectedError,
                expectedMessage,
                expectedPath
        );

        // Assert
        assertEquals(expectedTimestamp, responseError.getTimestamp());
        assertEquals(expectedStatus, responseError.getStatus());
        assertEquals(expectedError, responseError.getError());
        assertEquals(expectedMessage, responseError.getMessage());
        assertEquals(expectedPath, responseError.getPath());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        LocalDateTime expectedTimestamp = LocalDateTime.now();
        int expectedStatus = 500;
        String expectedError = "Internal Server Error";
        String expectedMessage = "Unexpected error occurred";
        String expectedPath = "/api/some-endpoint";

        // Act
        GenericResponseError error1 = new GenericResponseError(
                expectedTimestamp,
                expectedStatus,
                expectedError,
                expectedMessage,
                expectedPath
        );
        GenericResponseError error2 = new GenericResponseError(
                expectedTimestamp,
                expectedStatus,
                expectedError,
                expectedMessage,
                expectedPath
        );

        // Assert
        assertEquals(error1, error2); // Tests equals() method generated by Lombok
        assertEquals(error1.hashCode(), error2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("GenericResponseError(timestamp=" + expectedTimestamp +
                ", status=" + expectedStatus +
                ", error=" + expectedError +
                ", message=" + expectedMessage +
                ", path=" + expectedPath + ")", error1.toString()); // Tests toString() method generated by Lombok
    }
}
