package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class NonceResponseDTOTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedNonce = "J_8u2wAflTi2l2wQh7P_HQ";
        String expectedNonceExpiresIn = "600";

        // Act
        NonceResponseDTO nonceResponseDTO = new NonceResponseDTO(expectedNonce, expectedNonceExpiresIn);

        // Assert
        assertEquals(expectedNonce, nonceResponseDTO.getNonce());
        assertEquals(expectedNonceExpiresIn, nonceResponseDTO.getNonceExpiresIn());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedNonce = "J_8u2wAflTi2l2wQh7P_HQ";
        String expectedNonceExpiresIn = "600";

        // Act
        NonceResponseDTO dto1 = new NonceResponseDTO(expectedNonce, expectedNonceExpiresIn);
        NonceResponseDTO dto2 = new NonceResponseDTO(expectedNonce, expectedNonceExpiresIn);

        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("NonceResponseDTO(nonce=" + expectedNonce +
                ", nonceExpiresIn=" + expectedNonceExpiresIn + ")", dto1.toString()); // Tests toString() method generated by Lombok
    }

}
