package es.in2.issuer.api.model.dto;

import es.in2.issuer.api.model.enums.SignatureType;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class SignatureConfigurationTest {

    @Test
    public void testConstructorAndGetters() {
        // Arrange
        SignatureType expectedType = SignatureType.COSE;
        Map<String, String> expectedParameters = new HashMap<>();
        expectedParameters.put("param1", "value1");
        expectedParameters.put("param2", "value2");

        // Act
        SignatureConfiguration signatureConfiguration = new SignatureConfiguration(expectedType, expectedParameters);

        // Assert
        assertEquals(expectedType, signatureConfiguration.getType());
        assertEquals(expectedParameters, signatureConfiguration.getParameters());
    }

    @Test
    public void lombokGeneratedMethodsTest() {
        // Arrange
        SignatureType expectedType = SignatureType.COSE;
        Map<String, String> expectedParameters = new HashMap<>();
        expectedParameters.put("param1", "value1");
        expectedParameters.put("param2", "value2");

        // Act
        SignatureConfiguration config1 = new SignatureConfiguration(expectedType, expectedParameters);
        SignatureConfiguration config2 = new SignatureConfiguration(expectedType, expectedParameters);

        // Assert
        assertEquals(config1, config2); // Tests equals() method generated by Lombok
        assertEquals(config1.hashCode(), config2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("SignatureConfiguration(type=" + expectedType +
                ", parameters=" + expectedParameters + ")", config1.toString()); // Tests toString() method generated by Lombok
    }

}
