package es.in2.issuer.api.model.dto;

import es.in2.issuer.api.model.enums.SignatureType;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SignatureRequestTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        SignatureConfiguration expectedConfiguration = new SignatureConfiguration(SignatureType.COSE, null);
        String expectedData = "sampleData";

        // Act
        SignatureRequest signatureRequest = new SignatureRequest(expectedConfiguration, expectedData);

        // Assert
        assertEquals(expectedConfiguration, signatureRequest.getConfiguration());
        assertEquals(expectedData, signatureRequest.getData());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        SignatureConfiguration expectedConfiguration = new SignatureConfiguration(SignatureType.COSE, null);
        String expectedData = "sampleData";

        // Act
        SignatureRequest request1 = new SignatureRequest(expectedConfiguration, expectedData);
        SignatureRequest request2 = new SignatureRequest(expectedConfiguration, expectedData);

        // Assert
        assertEquals(request1, request2); // Tests equals() method generated by Lombok
        assertEquals(request1.hashCode(), request2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("SignatureRequest(configuration=" + expectedConfiguration +
                ", data=" + expectedData + ")", request1.toString()); // Tests toString() method generated by Lombok
    }

}
