package es.in2.issuer.api.model.dto;

import es.in2.issuer.api.model.enums.SignatureType;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class SignedDataTest {

    @Test
    public void testConstructorAndGetters() {
        // Arrange
        SignatureType expectedType = SignatureType.COSE;
        String expectedData = "sampleData";

        // Act
        SignedData signedData = new SignedData(expectedType, expectedData);

        // Assert
        assertEquals(expectedType, signedData.getType());
        assertEquals(expectedData, signedData.getData());
    }

    @Test
    public void defaultConstructorTest() {
        // Arrange
        SignatureType expectedDefaultType = SignatureType.JADES;
        String expectedDefaultData = "";

        // Act
        SignedData signedData = new SignedData();

        // Assert
        assertEquals(expectedDefaultType, signedData.getType());
        assertEquals(expectedDefaultData, signedData.getData());
    }

    @Test
    public void lombokGeneratedMethodsTest() {
        // Arrange
        SignatureType expectedType = SignatureType.COSE;
        String expectedData = "sampleData";

        // Act
        SignedData data1 = new SignedData(expectedType, expectedData);
        SignedData data2 = new SignedData(expectedType, expectedData);

        // Assert
        assertEquals(data1, data2); // Tests equals() method generated by Lombok
        assertEquals(data1.hashCode(), data2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("SignedData(type=" + expectedType +
                ", data=" + expectedData + ")", data1.toString()); // Tests toString() method generated by Lombok
    }
}
