package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class VerifiableCredentialJWTTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedToken = "sampleToken";

        // Act
        VerifiableCredentialJWT jwt = new VerifiableCredentialJWT(expectedToken);

        // Assert
        assertEquals(expectedToken, jwt.getToken());
    }

    @Test
    void testSetters() {
        // Arrange
        VerifiableCredentialJWT jwt = new VerifiableCredentialJWT();

        // Act
        jwt.setToken("newToken");

        // Assert
        assertEquals("newToken", jwt.getToken());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedToken = "sampleToken";

        // Act
        VerifiableCredentialJWT jwt1 = new VerifiableCredentialJWT(expectedToken);
        VerifiableCredentialJWT jwt2 = new VerifiableCredentialJWT(expectedToken);

        // Assert
        assertEquals(jwt1, jwt2); // Tests equals() method generated by Lombok
        assertEquals(jwt1.hashCode(), jwt2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("VerifiableCredentialJWT(token=" + expectedToken + ")", jwt1.toString()); // Tests toString() method generated by Lombok
    }
}
