package es.in2.issuer.api.model.dto;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class VerifiableCredentialResponseDTOTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange

        String expectedFormat = "jwt_vc_json";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        List<VerifiableCredentialDTO> expectedCredentials = List.of(
                new VerifiableCredentialDTO(
                        expectedFormat,
                        expectedCredential,
                        expectedCNonce,
                        expectedCNonceExpiresIn
                )
        );

        // Act
        VerifiableCredentialResponseDTO responseDTO = new VerifiableCredentialResponseDTO(expectedCredentials);

        // Assert
        assertEquals(expectedCredentials, responseDTO.getCredentials());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange

        String expectedFormat = "jwt_vc_json";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        List<VerifiableCredentialDTO> expectedCredentials = List.of(
                new VerifiableCredentialDTO(
                        expectedFormat,
                        expectedCredential,
                        expectedCNonce,
                        expectedCNonceExpiresIn
                )
        );

        // Act
        VerifiableCredentialResponseDTO dto1 = new VerifiableCredentialResponseDTO(expectedCredentials);
        VerifiableCredentialResponseDTO dto2 = new VerifiableCredentialResponseDTO(expectedCredentials);

        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
        assertEquals("VerifiableCredentialResponseDTO(credentials=" + expectedCredentials + ")", dto1.toString()); // Tests toString() method generated by Lombok
    }
}
