@startuml

autonumber

boundary "Wallet" as wallet
boundary "Issuer VCI" as issuerVCI
boundary "Authentic Sources" as authSources
boundary "Remote Signature" as remoteSignature

wallet -> wallet++: Create Credential Request
wallet -> wallet: Build dynamic ur to get Credential
wallet -> issuerVCI++: Request Credential \n POST /credentials
issuerVCI -> issuerVCI: Get the KID of header proof \n (did:key)
issuerVCI -> issuerVCI: Get the format \n (jwt_vc_json)
issuerVCI -> authSources++: Request user data
authSources -> issuerVCI--: 200 OK user_data
issuerVCI -> issuerVCI: Generate the Credential \n (from credential_template + user_data)
issuerVCI -> remoteSignature++: Sign Credential
remoteSignature -> remoteSignature: Get signature from Digital Certificate
remoteSignature -> remoteSignature: Sign the Credential with JAdES
remoteSignature -> issuerVCI--: 200 OK verifiable_credential
issuerVCI -> issuerVCI: Create Credential Response
issuerVCI -> wallet: 200 OK credential_response
wallet -> wallet: Save Credential


@enduml