package es.in2.issuer.domain.model;

import es.in2.issuer.domain.model.AppNonceValidationResponse;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppNonceValidationResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedAccessToken = "eyJhbGciOiJSUzI1Ni...yE1XAP-LrbAtaX-wln0wQgdXfu4dephCsMA";
        // Act
        AppNonceValidationResponse dto = new AppNonceValidationResponse(expectedAccessToken);
        // Assert
        assertEquals(expectedAccessToken, dto.accessToken());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedAccessToken = "eyJhbGciOiJSUzI1Ni...yE1XAP-LrbAtaX-wln0wQgdXfu4dephCsMA";
        String toStringDto = "AppNonceValidationResponseDTO(accessToken=eyJhbGciOiJSUzI1Ni...yE1XAP-LrbAtaX-wln0wQgdXfu4dephCsMA)";
        // Act
        AppNonceValidationResponse dto1 = new AppNonceValidationResponse(expectedAccessToken);
        AppNonceValidationResponse dto2 = new AppNonceValidationResponse(expectedAccessToken);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
