//package es.in2.issuer.domain.model;
//
//import org.junit.jupiter.api.Test;
//
//import java.util.HashMap;
//import java.util.List;
//import java.util.Map;
//
//import static org.junit.jupiter.api.Assertions.assertEquals;
//
//class CustomCredentialOfferTest {
//
//    @Test
//    void testConstructorAndGetters() {
//        // Arrange
//        String expectedCredentialIssuer = "https://credential-issuer.example.com";
//        List<CustomCredentialOffer.Credential> expectedCredentials = List.of(CustomCredentialOffer.Credential.builder().format("format").types(List.of("type")).build());
//        Map<String, Grant> expectedGrants = new HashMap<>();
//        expectedGrants.put("grant1", new Grant("type1", false));
//        expectedGrants.put("grant2", new Grant("type2", false));
//        // Act
//        CustomCredentialOffer credentialOffer = new CustomCredentialOffer(
//                expectedCredentialIssuer,
//                expectedCredentials,
//                expectedGrants
//        );
//        // Assert
//        assertEquals(expectedCredentialIssuer, credentialOffer.credentialIssuer());
//        assertEquals(expectedCredentials, credentialOffer.credentials());
//        assertEquals(expectedGrants, credentialOffer.grants());
//    }
//
//    @Test
//    void testSetters() {
//        // Arrange
//        String newCredentialIssuer = "https://new-credential-issuer.example.com";
//        List<CustomCredentialOffer.Credential> newCredentials = List.of(CustomCredentialOffer.Credential.builder().format("format").types(List.of("type")).build());
//        Map<String, Grant> newGrants = new HashMap<>();
//        // Act
//        CustomCredentialOffer customCredentialOffer = CustomCredentialOffer.builder().credentialIssuer(newCredentialIssuer).credentials(newCredentials).grants(newGrants).build();
//        // Assert
//        assertEquals(newCredentialIssuer, customCredentialOffer.credentialIssuer());
//        assertEquals(newCredentials, customCredentialOffer.credentials());
//        assertEquals(newGrants, customCredentialOffer.grants());
//    }
//
//    @Test
//    void lombokGeneratedMethodsTest() {
//        // Arrange
//        String expectedCredentialIssuer = "https://credential-issuer.example.com";
//        List<CustomCredentialOffer.Credential> expectedCredentials = List.of(CustomCredentialOffer.Credential.builder().format("format").types(List.of("type")).build());
//        Map<String, Grant> expectedGrants = new HashMap<>();
//        expectedGrants.put("grant1", new Grant("type1", false));
//        expectedGrants.put("grant2", new Grant("type2", false));
//        // Act
//        CustomCredentialOffer offer1 = new CustomCredentialOffer(
//                expectedCredentialIssuer,
//                expectedCredentials,
//                expectedGrants
//        );
//        CustomCredentialOffer offer2 = new CustomCredentialOffer(
//                expectedCredentialIssuer,
//                expectedCredentials,
//                expectedGrants
//        );
//        // Assert
//        assertEquals(offer1, offer2); // Tests equals() method generated by Lombok
//        assertEquals(offer1.hashCode(), offer2.hashCode()); // Tests hashCode() method generated by Lombok
//    }
//
//}
