package es.in2.issuer.domain.model;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class NonceResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedNonce = "J_8u2wAflTi2l2wQh7P_HQ";
        String expectedNonceExpiresIn = "600";
        // Act
        NonceResponse nonceResponse = new NonceResponse(expectedNonce, expectedNonceExpiresIn);
        // Assert
        assertEquals(expectedNonce, nonceResponse.nonce());
        assertEquals(expectedNonceExpiresIn, nonceResponse.nonceExpiresIn());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedNonce = "J_8u2wAflTi2l2wQh7P_HQ";
        String expectedNonceExpiresIn = "600";
        // Act
        NonceResponse dto1 = new NonceResponse(expectedNonce, expectedNonceExpiresIn);
        NonceResponse dto2 = new NonceResponse(expectedNonce, expectedNonceExpiresIn);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
