package es.in2.issuer.domain.model;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class VerifiableCredentialResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedFormat = "jwt_vc_json";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        List<VerifiableCredential> expectedCredentials = List.of(new VerifiableCredential(
                        expectedFormat,
                        expectedCredential,
                        expectedCNonce, expectedCNonceExpiresIn)
        );

        // Act
        VerifiableCredentialResponse responseDTO = new VerifiableCredentialResponse(expectedCredentials);

        // Assert
        assertEquals(expectedCredentials, responseDTO.credentials());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedFormat = "jwt_vc_json";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        List<VerifiableCredential> expectedCredentials = List.of(new VerifiableCredential(
                        expectedFormat,
                        expectedCredential,
                        expectedCNonce,
                        expectedCNonceExpiresIn
                )
        );
        // Act
        VerifiableCredentialResponse dto1 = new VerifiableCredentialResponse(expectedCredentials);
        VerifiableCredentialResponse dto2 = new VerifiableCredentialResponse(expectedCredentials);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
