package es.in2.issuer.domain.model;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.assertEquals;

class VerifiableCredentialResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedFormat = "jwt_vc_json";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;

        // Act
        VerifiableCredentialResponse responseDTO = new VerifiableCredentialResponse(expectedFormat, expectedCredential, expectedCNonce, expectedCNonceExpiresIn);

        // Assert
        assertEquals(expectedCredential, responseDTO.credential());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedFormat = "jwt_vc_json";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;

        // Act
        VerifiableCredentialResponse dto1 = new VerifiableCredentialResponse(expectedFormat, expectedCredential, expectedCNonce, expectedCNonceExpiresIn);
        VerifiableCredentialResponse dto2 = new VerifiableCredentialResponse(expectedFormat, expectedCredential, expectedCNonce, expectedCNonceExpiresIn);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
